use agenda_kaira;


CREATE TABLE carrito_usuarios( 
ID_USUARIO INT, 
CEDULA VARCHAR(10), 
NOMBRE_APELLIDO VARCHAR(60), 
CORREO VARCHAR(30), 
CLAVE VARCHAR(32), 
TIPO_USUARIO VARCHAR(20));


CREATE TABLE carrito_productos( 
ID_PRODUCTO INT AUTO_INCREMENT, 
NOMBRE_PRODUCTO VARCHAR(40), 
DESCRIPCION TEXT, 
NOMBRE_ARCHIVO VARCHAR(30), 
PRECIO DECIMAL(13.2), 
EXISTENCIA MEDIUMINT UNSIGNED, 
PRIMARY KEY (ID_PRODUCTO)); 


CREATE TABLE carrito_agregar( 
SESSION_ID  VARCHAR(26), 
ID_PRODUCTO INT); 


CREATE TABLE carrito_compras( 
ID_USUARIO INT, 
ID_PRODUCTO INT, 
CANTIDAD MEDIUMINT UNSIGNED, 
FECHA DATE); 