create database carrito_kaira;

\c carrito_kaira;


CREATE TABLE usuarios( 
ID_USUARIO serial, 
CEDULA VARCHAR(10), 
NOMBRE_APELLIDO VARCHAR(60), 
CORREO VARCHAR(30), 
CLAVE VARCHAR(32), 
TIPO_USUARIO VARCHAR(20),
primary key(ID_USUARIO),
unique(CORREO));

\d usuarios

CREATE TABLE productos( 
ID_PRODUCTO serial, 
NOMBRE_PRODUCTO VARCHAR(40), 
DESCRIPCION TEXT, 
NOMBRE_ARCHIVO VARCHAR(30), 
PRECIO numeric(13,2), 
EXISTENCIA integer, 
PRIMARY KEY (ID_PRODUCTO)); 


CREATE TABLE agregar( 
SESSION_ID  VARCHAR(26), 
ID_PRODUCTO INT); 


CREATE TABLE compras( 
ID_USUARIO INT, 
ID_PRODUCTO INT, 
CANTIDAD integer,
FECHA DATE); 


insert into usuarios(CEDULA, NOMBRE_APELLIDO, CORREO, CLAVE, TIPO_USUARIO) values
('V12345678', 'Carmen Lopez', 'Carmen@gmail.com', md5('V12345678'), 'Administrador');
