-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS transporte.autobuses
(
    id serial,
    marca_id integer,
    modelo_id integer,
    anio smallint,
    color_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transporte.marca
(
    id serial,
    nombre character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transporte.modelos
(
    id serial,
    nombre character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transporte.color
(
    id serial,
    nombre character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transporte.choferes
(
    id serial,
    nombre character varying(50),
    apellido character varying(50),
    cedula character varying(9),
    numero_licencia character varying(9),
    edad smallint,
    PRIMARY KEY (id),
    UNIQUE (cedula)
);

CREATE TABLE IF NOT EXISTS transporte.rutas
(
    id serial,
    nombre_ruta character varying(50),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transporte.paradas
(
    id serial,
    nombre character varying(50),
    ruta_id integer,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS transporte.recorridos
(
    autobuses_id integer,
    rutas_id integer
);

CREATE TABLE IF NOT EXISTS transporte.turnos
(
    id serial,
    nombre character varying(50),
    hora_inicio time without time zone,
    hora_finalizacion time without time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS transporte.autobuses
    ADD FOREIGN KEY (marca_id)
    REFERENCES transporte.marca (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.autobuses
    ADD FOREIGN KEY (modelo_id)
    REFERENCES transporte.modelos (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.autobuses
    ADD FOREIGN KEY (color_id)
    REFERENCES transporte.color (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.paradas
    ADD FOREIGN KEY (ruta_id)
    REFERENCES transporte.rutas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.recorridos
    ADD FOREIGN KEY (autobuses_id, rutas_id)
    REFERENCES transporte.autobuses (id, id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.recorridos
    ADD FOREIGN KEY (rutas_id)
    REFERENCES transporte.rutas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;