-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS transporte.autobuses DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS transporte.autobuses DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS transporte.autobuses DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS transporte.recorridos DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS transporte.recorridos DROP CONSTRAINT IF EXISTS None;

ALTER TABLE IF EXISTS transporte.paradas DROP CONSTRAINT IF EXISTS None;



DROP TABLE IF EXISTS transporte.autobuses;

CREATE TABLE IF NOT EXISTS transporte.autobuses
(
    id serial,
    marca_id integer,
    modelo_id integer,
    anio smallint,
    color_id integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.marcas;

CREATE TABLE IF NOT EXISTS public.marcas
(
    id serial,
    nombre character varying(50),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS public.modelo;

CREATE TABLE IF NOT EXISTS public.modelo
(
    id serial,
    nombre character varying(50),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS transporte.colores;

CREATE TABLE IF NOT EXISTS transporte.colores
(
    id serial,
    nombre character varying(50),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS transporte.choferes;

CREATE TABLE IF NOT EXISTS transporte.choferes
(
    id serial,
    nombre character varying(50),
    apellido character varying(50),
    cedula character varying(9),
    nro_licencia character varying(9),
    edad smallint,
    PRIMARY KEY (id),
    UNIQUE (cedula)
);

DROP TABLE IF EXISTS transporte.rutas;

CREATE TABLE IF NOT EXISTS transporte.rutas
(
    id serial,
    nombre character varying(50),
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS transporte.recorridos;

CREATE TABLE IF NOT EXISTS transporte.recorridos
(
    autobus_id integer,
    ruta_id integer,
    PRIMARY KEY (id, autobus_id, ruta_id)
);

DROP TABLE IF EXISTS transporte.paradas;

CREATE TABLE IF NOT EXISTS transporte.paradas
(
    id serial,
    nombre character varying(50),
    ruta_id integer,
    PRIMARY KEY (id)
);

DROP TABLE IF EXISTS transporte.turnos;

CREATE TABLE IF NOT EXISTS transporte.turnos
(
    id serial,
    nombre character varying(50),
    hora_inicio time without time zone,
    hora_finalizacion time without time zone,
    PRIMARY KEY (id)
);

ALTER TABLE IF EXISTS transporte.autobuses
    ADD FOREIGN KEY (marca_id)
    REFERENCES public.marcas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.autobuses
    ADD FOREIGN KEY (modelo_id)
    REFERENCES public.modelo (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.autobuses
    ADD FOREIGN KEY (color_id)
    REFERENCES transporte.colores (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.recorridos
    ADD FOREIGN KEY (autobus_id)
    REFERENCES transporte.autobuses (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.recorridos
    ADD FOREIGN KEY (ruta_id)
    REFERENCES transporte.rutas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS transporte.paradas
    ADD FOREIGN KEY (ruta_id)
    REFERENCES transporte.rutas (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;